//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigRate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act
    {
        public Act()
        {
            this.Performances = new HashSet<Performance>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GenreId { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Performance> Performances { get; set; }
    }
}
