//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigRate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInstanceStage
    {
        public EventInstanceStage()
        {
            this.Performances = new HashSet<Performance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> EventInstanceId { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual ICollection<Performance> Performances { get; set; }
        public virtual EventInstance EventInstance { get; set; }
    }
}
