//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigRate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceRating
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> PerformanceId { get; set; }
    
        public virtual Performance Performance { get; set; }
    }
}
